<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>비동기작업</title>
</head>
<body>
<h1>Promise - 예외처리: catch(onRejection)</h1>
<script>
const promise = new Promise((resolve, reject) => {
  throw '오류 발생!!!';
});

// promise 오류에 대해 여러 개의 reject 핸들러가 등록되어 있으면 
// 순차적으로 모두 호출된다.
promise.then(undefined, 
             () => console.log("rejected!"));
promise.catch(() => console.log("catched!"));

console.log("끝!");

</script>
</body>
</html>